import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

async function main() {
  console.log('Start seeding...')

  const anbieterData = [
    {
      slug: 'einhundert',
      name: 'EINHUNDERT Energie GmbH',
      kurzBeschreibung: 'Full-Service: PV-Installation, Finanzierung, digitale Zähler, Abrechnung, Mieter-App.',
      beschreibung: 'EINHUNDERT Energie ist einer der führenden Full-Service-Partner für Mieterstrom und Gebäudeversorgung.',
      standort: 'Köln',
      gruendungsjahr: 2017,
      planungKonzeption: true,
      finanzierung: true,
      installationPV: true,
      bhkw: false,
      wallboxen: true,
      speicher: true,
      messkonzept: true,
      abrechnungssoftware: true,
      mieterkommunikation: true,
      wartungBetrieb: true,
      reststromversorgung: true,
      mieterApp: true,
      modellMieterstrom: true,
      modellGGV: false,
      modellContracting: true,
      modellLieferkette: false,
      mindestWE: 4,
      investitionDurch: 'anbieter',
      renditeMin: 5,
      renditeMax: 12,
      ersparnisMin: 10,
      ersparnisMax: 20,
      regionen: 'bundesweit',
    },
    {
      slug: 'polarstern',
      name: 'Polarstern Energie',
      kurzBeschreibung: 'Full-Service: PV, BHKW, E-Mobilität, Contracting.',
      beschreibung: 'Polarstern bietet bundesweit Mieterstrom- und Contracting-Lösungen an.',
      standort: 'München',
      gruendungsjahr: 2011,
      planungKonzeption: true,
      finanzierung: true,
      installationPV: true,
      bhkw: true,
      wallboxen: true,
      speicher: true,
      messkonzept: true,
      abrechnungssoftware: true,
      mieterkommunikation: true,
      wartungBetrieb: true,
      reststromversorgung: true,
      mieterApp: true,
      modellMieterstrom: true,
      modellGGV: false,
      modellContracting: true,
      modellLieferkette: true,
      mindestWE: 6,
      investitionDurch: 'beide',
      renditeMin: 6,
      renditeMax: 14,
      ersparnisMin: 10,
      ersparnisMax: 15,
      regionen: 'bundesweit',
    },
    {
      slug: 'naturstrom',
      name: 'Naturstrom AG',
      kurzBeschreibung: 'Full-Service inkl. eigener Kraftwerkspark.',
      beschreibung: 'Naturstrom ist einer der größten unabhängigen Ökostromanbieter in Deutschland.',
      standort: 'Düsseldorf',
      gruendungsjahr: 1998,
      planungKonzeption: true,
      finanzierung: true,
      installationPV: true,
      bhkw: true,
      wallboxen: true,
      speicher: true,
      messkonzept: true,
      abrechnungssoftware: true,
      mieterkommunikation: true,
      wartungBetrieb: true,
      reststromversorgung: true,
      mieterApp: true,
      modellMieterstrom: true,
      modellGGV: false,
      modellContracting: true,
      modellLieferkette: false,
      mindestWE: 50,
      investitionDurch: 'anbieter',
      renditeMin: 5,
      renditeMax: 10,
      ersparnisMin: 8,
      ersparnisMax: 15,
      regionen: 'bundesweit',
    },
    {
      slug: 'solarimo',
      name: 'Solarimo GmbH (ENGIE)',
      kurzBeschreibung: '100% auf Mieterstrom fokussiert, Teil der ENGIE-Gruppe.',
      beschreibung: 'Solarimo plant, installiert und betreibt Solaranlagen für Mieterstrom.',
      standort: 'Berlin',
      gruendungsjahr: 2017,
      planungKonzeption: true,
      finanzierung: true,
      installationPV: true,
      bhkw: false,
      wallboxen: true,
      speicher: true,
      messkonzept: true,
      abrechnungssoftware: true,
      mieterkommunikation: true,
      wartungBetrieb: true,
      reststromversorgung: true,
      mieterApp: false,
      modellMieterstrom: true,
      modellGGV: false,
      modellContracting: true,
      modellLieferkette: false,
      mindestWE: 10,
      investitionDurch: 'anbieter',
      renditeMin: 5,
      renditeMax: 12,
      ersparnisMin: 10,
      ersparnisMax: 15,
      regionen: 'bundesweit',
    },
    {
      slug: 'metergrid',
      name: 'Metergrid',
      kurzBeschreibung: 'Schwerpunkt: SaaS-Plattform für Mieterstrom-Verwaltung & Abrechnung.',
      beschreibung: 'Metergrid liefert die Software für die eigenständige Mieterstrom-Umsetzung.',
      standort: 'Stuttgart',
      gruendungsjahr: 2020,
      planungKonzeption: false,
      finanzierung: false,
      installationPV: false,
      bhkw: false,
      wallboxen: false,
      speicher: false,
      messkonzept: true,
      abrechnungssoftware: true,
      mieterkommunikation: true,
      wartungBetrieb: false,
      reststromversorgung: false,
      mieterApp: true,
      modellMieterstrom: true,
      modellGGV: true,
      modellContracting: false,
      modellLieferkette: false,
      mindestWE: 3,
      investitionDurch: 'eigentuemer',
      renditeMin: 8,
      renditeMax: 17,
      ersparnisMin: 10,
      ersparnisMax: 20,
      regionen: 'bundesweit',
    },
    {
      slug: 'quartierkraft',
      name: 'Quartierkraft',
      kurzBeschreibung: 'Komplettlösung: Automatisierte Abrechnung und Betrieb.',
      beschreibung: 'Quartierkraft ist ein Startup für die einfache Umsetzung von GGV und Mieterstrom.',
      standort: 'Deutschland',
      gruendungsjahr: 2021,
      planungKonzeption: true,
      finanzierung: false,
      installationPV: false,
      bhkw: false,
      wallboxen: false,
      speicher: false,
      messkonzept: true,
      abrechnungssoftware: true,
      mieterkommunikation: true,
      wartungBetrieb: false,
      reststromversorgung: false,
      mieterApp: false,
      modellMieterstrom: true,
      modellGGV: true,
      modellContracting: false,
      modellLieferkette: false,
      mindestWE: 3,
      investitionDurch: 'eigentuemer',
      renditeMin: 8,
      renditeMax: 17,
      ersparnisMin: 10,
      ersparnisMax: 20,
      regionen: 'bundesweit',
    },
    {
      slug: 'pionierkraft',
      name: 'Pionierkraft',
      kurzBeschreibung: 'Energy-Sharing-Lösung außerhalb des EEG-Mieterstroms.',
      beschreibung: 'Pionierkraft ermöglicht die gemeinsame Stromnutzung in Mehrfamilienhäusern.',
      standort: 'München',
      gruendungsjahr: 2019,
      planungKonzeption: true,
      finanzierung: false,
      installationPV: false,
      bhkw: false,
      wallboxen: false,
      speicher: false,
      messkonzept: false,
      abrechnungssoftware: true,
      mieterkommunikation: true,
      wartungBetrieb: false,
      reststromversorgung: false,
      mieterApp: false,
      modellMieterstrom: false,
      modellGGV: true,
      modellContracting: false,
      modellLieferkette: false,
      mindestWE: 2,
      investitionDurch: 'eigentuemer',
      renditeMin: 7,
      renditeMax: 15,
      ersparnisMin: 10,
      ersparnisMax: 25,
      regionen: 'bundesweit',
    },
    {
      slug: 'buzzn',
      name: 'BUZZN',
      kurzBeschreibung: 'Pionier, Community-Ansatz "People Power".',
      beschreibung: 'BUZZN bietet Community-basierten Strommarkt und Mieterstrom.',
      standort: 'München',
      gruendungsjahr: 2010,
      planungKonzeption: false,
      finanzierung: false,
      installationPV: false,
      bhkw: false,
      wallboxen: false,
      speicher: false,
      messkonzept: false,
      abrechnungssoftware: true,
      mieterkommunikation: true,
      wartungBetrieb: false,
      reststromversorgung: false,
      mieterApp: true,
      modellMieterstrom: true,
      modellGGV: true,
      modellContracting: false,
      modellLieferkette: false,
      mindestWE: 2,
      investitionDurch: 'eigentuemer',
      renditeMin: 6,
      renditeMax: 12,
      ersparnisMin: 8,
      ersparnisMax: 15,
      regionen: 'bundesweit',
    },
    {
      slug: 'dach-fuer-dach',
      name: 'Dach für Dach',
      kurzBeschreibung: 'Unterstützung bei Wirtschaftlichkeitsrechnung & Abrechnung.',
      beschreibung: 'Experten für die Planung und Umsetzung.',
      standort: 'Deutschland',
      gruendungsjahr: 2018,
      planungKonzeption: true,
      finanzierung: false,
      installationPV: false,
      bhkw: false,
      wallboxen: false,
      speicher: false,
      messkonzept: false,
      abrechnungssoftware: true,
      mieterkommunikation: false,
      wartungBetrieb: false,
      reststromversorgung: false,
      mieterApp: false,
      modellMieterstrom: true,
      modellGGV: true,
      modellContracting: false,
      modellLieferkette: false,
      mindestWE: 3,
      investitionDurch: 'eigentuemer',
      renditeMin: 5,
      renditeMax: 15,
      ersparnisMin: 10,
      ersparnisMax: 20,
      regionen: 'bundesweit',
    },
    {
      slug: 'green-planet-energy',
      name: 'Green Planet Energy',
      kurzBeschreibung: 'Genossenschaftlich organisiert, ehemals Greenpeace Energy.',
      beschreibung: 'Bundesweit agierender Ökostromanbieter.',
      standort: 'Hamburg',
      gruendungsjahr: 1999,
      planungKonzeption: true,
      finanzierung: true,
      installationPV: true,
      bhkw: true,
      wallboxen: false,
      speicher: true,
      messkonzept: true,
      abrechnungssoftware: true,
      mieterkommunikation: true,
      wartungBetrieb: true,
      reststromversorgung: true,
      mieterApp: false,
      modellMieterstrom: true,
      modellGGV: false,
      modellContracting: true,
      modellLieferkette: false,
      mindestWE: 10,
      investitionDurch: 'beide',
      renditeMin: 5,
      renditeMax: 10,
      ersparnisMin: 8,
      ersparnisMax: 12,
      regionen: 'bundesweit',
    },
    {
      slug: 'getec',
      name: 'GETEC',
      kurzBeschreibung: 'Großer Energiedienstleister, Full-Service-Contracting.',
      beschreibung: 'Spezialisiert auf Quartierskonzepte.',
      standort: 'Magdeburg',
      gruendungsjahr: 1993,
      planungKonzeption: true,
      finanzierung: true,
      installationPV: true,
      bhkw: true,
      wallboxen: true,
      speicher: true,
      messkonzept: true,
      abrechnungssoftware: true,
      mieterkommunikation: true,
      wartungBetrieb: true,
      reststromversorgung: true,
      mieterApp: false,
      modellMieterstrom: true,
      modellGGV: false,
      modellContracting: true,
      modellLieferkette: false,
      mindestWE: 20,
      investitionDurch: 'anbieter',
      renditeMin: 4,
      renditeMax: 9,
      ersparnisMin: 10,
      ersparnisMax: 15,
      regionen: 'bundesweit',
    },
    {
      slug: 'naturenergie',
      name: 'naturenergie (Südbaden)',
      kurzBeschreibung: 'Regional (Südbaden/Süddeutschland), ab 30 WE.',
      beschreibung: 'Regionaler Anbieter für Contracting und Mieterstrom.',
      standort: 'Südbaden',
      gruendungsjahr: 1998,
      planungKonzeption: true,
      finanzierung: true,
      installationPV: true,
      bhkw: true,
      wallboxen: true,
      speicher: true,
      messkonzept: true,
      abrechnungssoftware: true,
      mieterkommunikation: true,
      wartungBetrieb: true,
      reststromversorgung: true,
      mieterApp: false,
      modellMieterstrom: true,
      modellGGV: false,
      modellContracting: true,
      modellLieferkette: false,
      mindestWE: 30,
      investitionDurch: 'anbieter',
      renditeMin: 5,
      renditeMax: 10,
      ersparnisMin: 8,
      ersparnisMax: 12,
      regionen: 'Südbaden, Süddeutschland',
    },
    {
      slug: 'white-energy',
      name: 'white energy GmbH',
      kurzBeschreibung: 'Plattform-Lösung für smarte und automatisierte Mieterstrom-Verwaltung (weMIETERSTROM).',
      beschreibung: 'white energy bietet eine digitale Gesamtlösung zur Steuerung, Abrechnung und Analyse der Energieströme im Gebäude.',
      standort: 'Wiesbaden',
      gruendungsjahr: 2018,
      planungKonzeption: true,
      finanzierung: false,
      installationPV: false,
      bhkw: false,
      wallboxen: true,
      speicher: true,
      messkonzept: true,
      abrechnungssoftware: true,
      mieterkommunikation: true,
      wartungBetrieb: false,
      reststromversorgung: true,
      mieterApp: true,
      modellMieterstrom: true,
      modellGGV: true,
      modellContracting: false,
      modellLieferkette: false,
      mindestWE: 3,
      investitionDurch: 'eigentuemer',
      renditeMin: 8,
      renditeMax: 15,
      ersparnisMin: 10,
      ersparnisMax: 20,
      regionen: 'bundesweit',
    },
    {
      slug: 'entena-energy',
      name: 'enTena Energy',
      kurzBeschreibung: 'Full-Service Energieversorger-Partner spezialisiert auf Mieterstrom mit Speicherhebel.',
      beschreibung: 'enTena übernimmt die vollständige kommerzielle Abwicklung (Abrechnung, EVU-Pflichten) und arbeitet eng mit lokalen Technik-Partnern wie Verdasol zusammen, um echte Autarkie zu erzielen.',
      standort: 'Deutschland',
      gruendungsjahr: 2023,
      planungKonzeption: true,
      finanzierung: true,
      installationPV: false,
      bhkw: false,
      wallboxen: true,
      speicher: true,
      messkonzept: true,
      abrechnungssoftware: true,
      mieterkommunikation: true,
      wartungBetrieb: true,
      reststromversorgung: true,
      mieterApp: true,
      modellMieterstrom: true,
      modellGGV: true,
      modellContracting: true,
      modellLieferkette: true,
      mindestWE: 6,
      investitionDurch: 'beide',
      renditeMin: 8,
      renditeMax: 15,
      ersparnisMin: 10,
      ersparnisMax: 15,
      regionen: 'bundesweit',
    }
  ]

  for (const a of anbieterData) {
    await prisma.anbieter.upsert({
      where: { slug: a.slug },
      update: a,
      create: a,
    })
  }

  // Foerdersaetze 2025/2026 Seed
  const foerderData = [
    { typ: 'mieterstromzuschlag', anlagenGroesseVon: 0, anlagenGroesseBis: 10, satz: 2.59, gueltigVon: new Date('2025-02-01'), gueltigBis: new Date('2025-07-31') },
    { typ: 'mieterstromzuschlag', anlagenGroesseVon: 10, anlagenGroesseBis: 40, satz: 2.41, gueltigVon: new Date('2025-02-01'), gueltigBis: new Date('2025-07-31') },
    { typ: 'mieterstromzuschlag', anlagenGroesseVon: 40, anlagenGroesseBis: 100, satz: 1.62, gueltigVon: new Date('2025-02-01'), gueltigBis: new Date('2025-07-31') },
    { typ: 'einspeiseverguetung', anlagenGroesseVon: 0, anlagenGroesseBis: 10, satz: 8.11, gueltigVon: new Date('2025-02-01'), gueltigBis: new Date('2025-07-31') },
    { typ: 'einspeiseverguetung', anlagenGroesseVon: 10, anlagenGroesseBis: 40, satz: 7.03, gueltigVon: new Date('2025-02-01'), gueltigBis: new Date('2025-07-31') },
    { typ: 'einspeiseverguetung', anlagenGroesseVon: 40, anlagenGroesseBis: 100, satz: 5.74, gueltigVon: new Date('2025-02-01'), gueltigBis: new Date('2025-07-31') }
  ]

  for (const f of foerderData) {
    await prisma.foerdersatz.create({ data: f })
  }

  // Blogposts Placeholder Seed
  await prisma.blogPost.upsert({
    where: { slug: 'mieterstrom-2025-2026' },
    update: {},
    create: {
      slug: 'mieterstrom-2025-2026',
      titel: 'Mieterstrom 2025/2026: Der komplette Leitfaden für Vermieter',
      excerpt: 'Alles was Sie über Mieterstrom im Jahr 2025 und 2026 wissen müssen. So steigern Sie die Rendite Ihrer Immobilien.',
      inhalt: `## Einleitung
Mieterstrom wird immer attraktiver. Durch das neue Solarpaket I von 2024 und die stabilisierten Fördersätze für 2025/2026 ist der Bau einer Photovoltaikanlage auf Mehrfamilienhäusern so rentabel wie nie.

### Was hat sich geändert?
1. **Bürokratieabbau**: Einfachere Anmeldung und entfallene Personenidentität zwischen Anlagenbetreiber und Stromverkäufer.
2. **Gebäudeversorgung (GGV)**: Ein völlig neues Modell nach § 42b EnWG (Gemeinschaftliche Gebäudeversorgung) erlaubt die unbürokratische Aufteilung des erzeugten Stroms ohne die restriktiven Pflichten des klassischen Mieterstroms (z.B. keine Reststromlieferpflicht).
3. **Speicherförderung**: Die Integration von großen Batteriespeichern wurde erleichtert.

Mit Modellen wie dem **Contracting** können Sie als Immobilienbesitzer völlig risikofrei agieren.`,
      kategorie: 'Recht',
      autor: 'Admin',
      veroeffentlicht: true
    }
  });

  await prisma.blogPost.upsert({
    where: { slug: 'gebaeudeversorgung-vs-mieterstrom' },
    update: {},
    create: {
      slug: 'gebaeudeversorgung-vs-mieterstrom',
      titel: 'Gebäudeversorgung (GGV) oder echter Mieterstrom?',
      excerpt: 'Die Novelle des Solarpakets I hat die GGV eingeführt. Doch welches Modell passt besser zu Ihrem Gebäude?',
      inhalt: `Die neue **Gemeinschaftliche Gebäudeversorgung (GGV)** löst viele Probleme des alten Mieterstrommodells. Aber sie ist nicht immer die bessere Wahl.

## Echter Mieterstrom (§ 42a EnWG)
Beim echten Mieterstrom werden Sie (oder Ihr Dienstleister) zum Energieversorger. Sie liefern dem Mieter ein Komplettpaket aus Solarstrom vom Dach und Reststrom aus dem Netz.
**Vorteile**:
- Mieterstromzuschlag (rund 2,5 ct/kWh Förderung)
- Höchste Rendite bei Vollausbau
- Alles aus einer Hand für den Mieter

## Gemeinschaftliche Gebäudeversorgung (§ 42b EnWG)
Hierbei wird nur der Solarstrom prozentual an die teilnehmenden Mieter aufgeteilt. Für den Reststrom behält der Mieter seinen eigenen, klassischen Stromvertrag bei den Stadtwerken.
**Vorteile**:
- **Keine Versorgerpflichten**: Sie müssen keinen Reststrom einkaufen.
- Kein bürokratischer Aufwand mit Kündigungen von Alt-Verträgen.
**Nachteil**: Kein staatlicher Mieterstromzuschlag aus dem EEG.

### Fazit
Für Projekte unter 10 Wohneinheiten ist die GGV oft die stressfreiere Variante. Ab 10 WE oder bei Einsatz eines Contractors (wie *enTena* oder *Polarstern*) ist der echte Mieterstrom aufgrund der Förderungen finanziell attraktiver.`,
      kategorie: 'Modelle',
      autor: 'Admin',
      veroeffentlicht: true
    }
  });

  await prisma.blogPost.upsert({
    where: { slug: 'storage-leverage-mieterstrom' },
    update: {},
    create: {
      slug: 'storage-leverage-mieterstrom',
      titel: 'Der Storage-Leverage: Warum sich Mieterstrom nur mit Batterie lohnt!',
      excerpt: 'Warum klassische PV-Anlagen ohne Speicher im Mehrfamilienhaus Potenzial verschenken und wie Sie die Autarkie auf über 60% steigern.',
      inhalt: `Die klassischen Verbrauchskurven in Wohngebäuden zeigen deutlich: Wenn die Sonne mittags am stärksten scheint, sind die meisten Mieter auf der Arbeit. Der meiste Strom wird abends und morgens benötigt.

## Das Problem der Eigenverbrauchsquote
Ohne Speichermedium liegt die sogenannte Eigenverbrauchsquote (der Teil des Solarstroms, der direkt im Gebäude verbraucht wird) in Mehrfamilienhäusern oft nur bei **25% bis 35%**. Der Rest wird für magere 7-8 Cent netzeingespeist.

## Die Lösung: Gewerbespeicher (Storage Leverage)
Durch die Integration eines großen Batteriespeichers (z.B. 20 - 50 kWh) lässt sich die Eigenverbrauchsquote massiv auf **60% bis über 70%** anheben.
Da der Mieterstrom für ca. 25 bis 30 Cent an die Mieter verkauft wird, steigt die Marge für den Betreiber enorm. Der Speicher "hebelt" die Skaleneffekte der großen Dach-Anlage.

Insbesondere im B2B-Umfeld oder bei innovativen Partnern wie *enTena* wird der Speicher stets als zentrales Element der Wirtschaftlichkeit betrachtet.`,
      kategorie: 'Wirtschaftlichkeit',
      autor: 'Admin',
      veroeffentlicht: true
    }
  });

  console.log('Seeding finished.')
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
